### PR TITLE
fix: use mixins for autocompletion

### PR DESCRIPTION
**Pull request by ju5t**
By using mixins, an IDE will know which methods are available in the facade.

### CODE REVIEW

**Comment by kevindierkx** [comment]
@ju5t Thanks for the contribution!

I'm fine with the change, could you run the PHPCS fixer by running `composer run phpcs-fix`? I'll make sure this is included in the next release when the CI/CD stops complaining.

**Comment by ju5t** [comment]
@kevindierkx no problem.

This did expose an issue with [Directives.php#L101](https://github.com/kevindierkx/laravel-domain-parser/blob/master/src/Directives.php#L101) though. PHPStan returns:

```
  101    Parameter #1 $host of static method Pdp\DomainNameResolver::resolve() expects Pdp\Host,
         int|Pdp\DomainNameProvider|Pdp\Host|string|Stringable|null given.
```

You're allowing much more in the doc block and I'm pretty sure it doesn't like that.

**Comment by kevindierkx** [comment]
@ju5t Thanks, those phpstan issues are a known issue #29 shouldn't break any code though ;)

**Comment by kevindierkx** [comment]
@ju5t Tagged 1.2.2 with your changes

**Comment by ju5t** [comment]
Thanks!

**Pull request merged**
