### PR TITLE
Added support for L6.x and L7.x, dropped support for PHP7.1 and L5.x

### LINKED ISSUE #2: Support for Laravel 6.x/7.x
Support for Laravel 6.x has already been proposed in: https://github.com/bakame-php/laravel-domain-parser/pull/1

For future support of Larvel 7.x and up I would suggest dropping support for older Laravel versions in future versions of this package. This would make testing a bit easier. I was playing around in the previously mentioned PR to support L5.x up till L7.x, but that resulted in the need of supporting 3 different versions of various testing packages and resulted in various errors related to them.

By removing L5.x we could up the PHP version requirement to 7.2, this is the minimal requirement of L6.x and update PHPStan to a more recent version.

### PR DESCRIPTION
**Pull request by kevindierkx**
This replaces https://github.com/bakame-php/laravel-domain-parser/pull/1 and resolves https://github.com/bakame-php/laravel-domain-parser/issues/2

**Notable changes:**
- Support for both L6.x and L7.x.
- Dropped support for L5.x.
- Updated PHPUnit, PHPStan and orchestra/testbench dependencies to match L6.x requirements.
- Updated PHPCS config to allow mixed in docblocks, this is required to pass the PHPStan tests.

\cc @nyamsprod

### CODE REVIEW

**Comment by nyamsprod** [comment]
@kevindierkx First it is a great PR so thanks for that. 

I have a couple of questions before merging this PR ? As I may have mention is the other PR , I think/hope I'm not that familiar with Laravel. This package was an excuse for an introduction to the Laravel ecosystem so I can get a test of what it looks like to develop for that specific framework. But to be honest since I do not use Laravel I'm not really best qualified to maintain it. So would you be interested in maintaining this package ? 

I am still maintaining the parent project but I do not have the time to invest in this particular package.

If you can not that's also fine you did a terrific job and I'll make sure to mention it once I've merge and tag the release in that case.

**Comment by kevindierkx** [comment]
@nyamsprod Thanks for the offer! I'm certainly open for dicussing further details and am open to help you out here. You can [send me an email](mailto:kevin@distortedfusion.com) to discuss further details.

**Comment by kevindierkx** [comment]
@nyamsprod Hey! Do you have any updates?

**Comment by nyamsprod** [comment]
@kevindierkx sorry for late response I'm really busy at the moment I'll make a full answer hopefully before saturday as I'll be on vacation then

**Comment by nyamsprod** [comment]
@kevindierkx my update is quite simple 👍   if you agree on me transfering to you this package I'll gladly do it 😉  . Then the package and its future will all yours to decide

**Comment by kevindierkx** [comment]
@nyamsprod Alright, sounds good to me 🙂

**Pull request merged**
