### PR TITLE
Adds support for Laravel 8

### LINKED ISSUE #7: Laravel 8.x support
Hello!~

Is Laravel 8.x support planned?

### PR DESCRIPTION
**Pull request by cfroystad**
Adds support for Laravel 8 and resolves #7

### CODE REVIEW

**Comment by cfroystad** [comment]
As far as I can tell, the build failure is unrelated to this change. Please correct me if I'm wrong

**Comment by kevindierkx** [comment]
Hey! Thanks for your contribution, it looks like my notification settings were a bit messed up and I completely missed this PR...

I'll need to transfer the testing to GitHub Actions due to recent changes at Travis. I'll keep this open for now until I fixed the tests.

Please also refer to #6, unrelated to this PR, but I'm planning to make some major changes to support the lastest base package and add support for PHP 8.x.

**Comment by kevindierkx** [comment]
@cfroystad Hey! I've updated the tests. Could you update your PR to reflect those changes?

In the meantime I'll work on supporting `jeremykendall/php-domain-parser:^6.0`. This will also introduce support for L8.*, but will include breaking changes. Please refer to #6

**Comment by cfroystad** [comment]
@kevindierkx Thanks for looking into this and your great job on this package!

I've rebased the PR on master. It's still failing in CI-CD / PHP:8 / Laravel:8 but the issue seems to be affecting the API of the package as a whole. Thus, I do not feel competent to decide if/how to change the API in order to make the final test pass.

The remaining issue is the parameter order of the __invoke function in ValidatorWrapper.php, where a non-default parameter is listed after a default-value parameter

**Comment by kevindierkx** [comment]
@cfroystad Thanks! I'll have to thank @nyamsprod for the great starting point though!

The failing tests for PHP 8.x are expected, various dependencies aren't completely or are only specificly compatible with PHP 8.x. For example php-cs-fixer is still working on complete PHP 8.x support and is therefore disabled in our current testing for PHP 8.x.

Something similar applies to Laravel, L8.x supports both PHP ^7.3 and PHP ^8.0, L6.x however does not... Besides the breaking changes in the View and Blade components, supporting all these versions of Laravel within one release wouldn't be reasonable.

I'll merge your changes, since they seem to be working with L8.x on PHP 7.4. However, I'm assuming you're targeting PHP 8.0 right?

**Pull request merged**
